### ISSUE TITLE
Unable to edit my business listing

### ISSUE THREAD

**Issue by mvidberg** [koad/gencapp.com#1]
I am now getting the following error
![mongoerror](https://cloud.githubusercontent.com/assets/871411/17213803/ff37a6b0-54a3-11e6-9d73-b2b44be07fea.png)
when trying to edit my business listing.  This comes up regardless if I'm setting a new logo or banner or not.

**Comment by ve-koad** [comment]
Repaired in f9d6e6c..ed13858

Autohooks could not set and unset a key.

**Comment by koad** [comment]
merged commit c8b5e1f
