### ISSUE TITLE
Prevent html tags from showing in the Your Businesses section

### ISSUE THREAD

**Issue by mvidberg** [koad/gencapp.com#10]
The html tags are showing in the description portion of Your Businesses listing on the My Gencapp page.  Probably could just strip tags and only show text as a preview here?

![stripthesetags](https://cloud.githubusercontent.com/assets/871411/17250174/308e3eb8-5571-11e6-9e4e-54086810c0b0.jpg)

**Comment by ve-koad** [comment]
Sorted this, will still show on tables but are to be replaced.
