### ISSUE TITLE
Getting data bleed over from previous session

### ISSUE THREAD

**Issue by mvidberg** [koad/gencapp.com#11]
I was logged in as mvidberg, then logged out and logged back in as socialvisio.  I see that my Social Verfication has mvidberg's properties instead of socialvisio's (which only should have email, twitter, gplus).  

![verificationbleed](https://cloud.githubusercontent.com/assets/871411/17250298/b422346e-5571-11e6-84cf-15927b37a31d.jpg)

**Comment by mvidberg** [comment]
Update: i created a selenium test user on littleberlin, then logged out, checked my repute values (they are blank), logged in again and check repute... now they have values for ve-koad in them.  so it is not a browser cache bleed, it's actually coming from the server since I've never logged in as ve-koad.

**Comment by ve-koad** [comment]
Added workflow checks and insured the deletion of data from previous pages.
