### ISSUE TITLE
Should show total counts

### ISSUE THREAD

**Issue by mvidberg** [koad/gencapp.com#17]
On the "Post a listing" page, both the Businesses and Projects just shows "using 0 of unlimited" for total count.
![count](https://cloud.githubusercontent.com/assets/871411/17344757/56a4602e-58d1-11e6-8536-9374d40eb956.jpg)

**Comment by ve-koad** [comment]
Fixed on LB, awaiting commit.

**Comment by ve-koad** [comment]
fixed
