### ISSUE TITLE
Use ISP's location button has stopped working

### ISSUE THREAD

**Issue by mvidberg** [koad/gencapp.com#24]
In Firefox, the "Click here to use your ISP's location" button has stopped working.   Just does nothing when I click.  Happens on both live and test server.
I don't get that button coming up in Chrome, so can't say if it works there or not.

**Comment by mvidberg** [comment]
Error on the event log is "ERROR    CLIENT::UNCAUGHT    /   hkpdBHLsHNRgccpBm   TypeError: a is undefined"

**Comment by ve-koad** [comment]
Fixed; data returning to client from method missing earlier data.
